version: '3'
services:
  BACpredictions: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: bac_prediction
    container_name: bac
    ports:
      - '4000:80'
    volumes:
      - .:/app
