version: '3'
services:
  TSLApredictions: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: tsla_prediction_final
    container_name: tsla
    ports:
      - '4000:80'
    volumes:
      - .:/app
