version: '3'
services:
  tsla_prediction: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: tsla_prediction
    container_name: tsla
    ports:
      - '4000:80'
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Paris
