version: '3'
services:
  AAPLpredictions: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: apple_prediction
    container_name: aapl
    ports:
      - '4000:80'
    volumes:
      - .:/app
