version: '3'
services:
  mrk_prediction: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: mrk_prediction
    container_name: mrk
    ports:
      - '4000:80'
    volumes:
      - .:/app
