# Use the official Ubuntu 20.04 image as the base image
FROM ubuntu:20.04

# Update the package list and install Python 3.8
RUN apt-get update && \
    apt-get install -y python3.8 && \
    apt-get install -y python3-pip && \
    apt-get clean

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file and install the dependencies
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app/

# Set the default command to run when a container starts
CMD ["python3", "pred.py"]