version: '3'
services:
  hpq_prediction: # name of project
    build:
      context: .                  #from where project files are taken and loaded
      dockerfile: Dockerfile.dev
    image: hpq_prediction
    container_name: hpq
    ports:
      - '4000:80'
    volumes:
      - C:/Temp:/app/temp
    environment:
      - TZ=Europe/Paris
